### ISSUE TITLE
Cinderella report

### ISSUE THREAD

**Issue by sghud1** [rbcavanaugh/mainConcept#24]
We've been using the app to score Cinderella samples, and my students have said they aren't able to download the report. I don't know if this is a server timeout issue...They can get to the results page and the final scores are correct, but no report download. I'll try to get more details, but wanted to put that out there.

**Comment by rbcavanaugh** [comment]
@sghud1 I think I've resolved this - some NA values in the norm file throwing an error (which is probably worth a discussion at some point...). Can you see if this is fixed when you try now?
