### ISSUE TITLE
Add elicitation instructions

### ISSUE THREAD

**Issue by sghud1** [rbcavanaugh/mainConcept#25]
I got this feedback from a clinician who has been using the app:

One area that could be integrated to increase efficiency with its use is to incorporate the initial directions for each discourse task ("Take a little time to look at the pictures. They tell a story. Take a look at all of them, and then I'll ask you to tell me the story with a beginning, a middle, and an end. You can look at the pictures as you tell the story.”) into the module or page before your open up the page to initiate scoring. This would provide all of the relevant information for the clinician to minimize switching back and forth with the AphasiaBank site to review the procedure.

I think this would be a relatively easy add, if ya'll agree that it would be beneficial

**Comment by rbcavanaugh** [comment]
yup! We started to do this, and then Davida and Brian updated talkback to have everything available online: https://aphasia.talkbank.org/protocol/english/investigator-aphasia/narrative.html. 

In lieu of doing this, I'd rather just link to their site. Is that ok?

**Comment by sghud1** [comment]
I think that's fine!
